### ISSUE TITLE
Cannot add middleware after an application has started

### ISSUE THREAD

**Issue by Someant** [camenduru/stable-diffusion-webui-docker#1]
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/webui.py", line 195, in <module>
    webui()
  File "/content/stable-diffusion-webui/webui.py", line 163, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started

**Comment by camenduru** [comment]
@Someant thanks for the notify ❤ please try it again

**Comment by camenduru** [comment]
I added this line `RUN sed -i '$a fastapi==0.90.0' /content/stable-diffusion-webui/requirements_versions.txt`
