### ISSUE TITLE
cannot build on mac m1 with docker desktop

### ISSUE THREAD

**Issue by harrywang** [camenduru/stable-diffusion-webui-docker#2]
Hi, I am trying to build the image using `docker build .` on mac m1 and run into many issues.

Hope you can help and thank you so much!

first `ModuleNotFoundError: No module named 'torch'`

```
=> ERROR [ 7/21] RUN pip install --pre xformers                                                                                           3.4s
------                                                                                                                                          
 > [ 7/21] RUN pip install --pre xformers:                                                                                                      
#10 0.397 Defaulting to user installation because normal site-packages is not writeable                                                         
#10 0.763 Collecting xformers                                                                                                                   
#10 1.054   Downloading xformers-0.0.17.dev466.tar.gz (7.4 MB)                                                                                  
#10 2.312      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 5.9 MB/s eta 0:00:00                                                         
#10 2.879   Preparing metadata (setup.py): started
#10 2.988   Preparing metadata (setup.py): finished with status 'error'
#10 2.990   error: subprocess-exited-with-error
#10 2.990   
#10 2.990   × python setup.py egg_info did not run successfully.
#10 2.990   │ exit code: 1
#10 2.990   ╰─> [6 lines of output]
#10 2.990       Traceback (most recent call last):
#10 2.990         File "<string>", line 2, in <module>
#10 2.990         File "<pip-setuptools-caller>", line 34, in <module>
#10 2.990         File "/tmp/pip-install-fxjxehjn/xformers_e15ca0b2eef3427fad5cc55bdcca5e7f/setup.py", line 23, in <module>
#10 2.990           import torch
#10 2.990       ModuleNotFoundError: No module named 'torch'
#10 2.990       [end of output]
#10 2.990   
#10 2.990   note: This error originates from a subprocess, and is likely not a problem with pip.
#10 2.991 error: metadata-generation-failed
#10 2.991 
#10 2.991 × Encountered error while generating package metadata.
#10 2.991 ╰─> See above for output.
#10 2.991 
#10 2.991 note: This is an issue with the package mentioned above, not pip.
#10 2.991 hint: See above for details.
------
```

fixed by adding:
```
RUN pip3 install --upgrade pip
RUN pip install torch
RUN pip install --pre xformers
```

then `ERROR: No matching distribution found for triton` I don't know what to do.

```
docker build .
[+] Building 2.3s (15/28)                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                       0.0s
 => => transferring dockerfile: 2.65kB                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                          0.0s
 => => transferring context: 2B                                                                                                            0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.7.1-base-ubuntu22.04                                                             1.3s
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                                                                                 0.0s
 => CANCELED https://huggingface.co/ckpt/anything-v4.5-vae-swapped/resolve/main/anything-v4.5-vae-swapped.safetensors                      0.9s
 => [ 1/22] FROM docker.io/nvidia/cuda:11.7.1-base-ubuntu22.04@sha256:ab51a8d50a8c7d5f0c61b4a3eaeaa72b99aa60c2235c8c1a8c87410d9172aba5     0.0s
 => CACHED https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-scripts/main/run_n_times.py                                  0.0s
 => CACHED [ 2/22] RUN apt-get update -y && apt-get upgrade -y && apt-get install -y libgl1 libglib2.0-0 wget git git-lfs python3-pip pyt  0.0s
 => CACHED [ 3/22] RUN adduser --disabled-password --gecos '' user                                                                         0.0s
 => CACHED [ 4/22] RUN mkdir /content && chown -R user:user /content                                                                       0.0s
 => CACHED [ 5/22] WORKDIR /content                                                                                                        0.0s
 => CACHED [ 6/22] RUN pip3 install --upgrade pip                                                                                          0.0s
 => CACHED [ 7/22] RUN pip install torch                                                                                                   0.0s
 => CACHED [ 8/22] RUN pip install --pre xformers                                                                                          0.0s
 => ERROR [ 9/22] RUN pip install --pre triton                                                                                             0.9s
------                                                                                                                                          
 > [ 9/22] RUN pip install --pre triton:
#13 0.406 Defaulting to user installation because normal site-packages is not writeable
#13 0.844 ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
#13 0.844 ERROR: No matching distribution found for triton
```

**Comment by WSINTRA** [comment]
https://pypi.org/project/triton/

**Comment by camenduru** [comment]
Hi @harrywang 👋 please delete 

```
RUN pip install --pre xformers
RUN pip install --pre triton
```
and  `--xformers`

and try again 

also check 

https://github.com/apple/ml-stable-diffusion
https://github.com/godly-devotion/MochiDiffusion
https://huggingface.co/coreml
