### ISSUE TITLE
ImportError: cannot import name 'FormColumn' from 'modules.ui_components' 

### ISSUE THREAD

**Issue by 20171130** [camenduru/stable-diffusion-webui-docker#7]
Thank you for your work.
Here is the error message I got when running `python webui.py --xformers --listen --enable-insecure-extension-access --gradio-queue ` inside the docker container build with `Dockerfile.Stable`. 
```
Error loading script: deforum.py                                                             [73/483]
Traceback (most recent call last):                                                                   
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts               
    script_module = script_loading.load_module(scriptfile.path)                                      
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module          
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py
", line 22, in <module>
    init_deforum()
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py
", line 14, in init_deforum                                                                          
    from deforum_helpers.ui_right import on_ui_tabs
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_he
lpers/ui_right.py", line 8, in <module>
    from .ui_left import setup_deforum_left_side_ui
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_he
lpers/ui_left.py", line 7, in <module>
    from .ui_elements import get_tab_run, get_tab_keyframes, get_tab_prompts, get_tab_init, get_tab_h
ybrid, get_tab_output
  File "/content/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_he
lpers/ui_elements.py", line 2, in <module>
    from modules.ui_components import FormRow, FormColumn
ImportError: cannot import name 'FormColumn' from 'modules.ui_components' (/content/stable-diffusion-
webui/modules/ui_components.py)
```

```
Error calling: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additi
onal_networks.py/ui
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_ne
tworks.py", line 104, in ui
    weight.release(lambda w: (w, w), inputs=[weight], outputs=[weight_unet, weight_tenc])
AttributeError: 'Slider' object has no attribute 'release'
```
```
Error executing callback ui_tabs_callback for /content/stable-diffusion-webui/extensions/sd-we[8/483]
itional-networks/scripts/additional_networks.py                                                      
Traceback (most recent call last):                                                                   
  File "/content/stable-diffusion-webui/modules/script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_ne
tworks.py", line 290, in on_ui_tabs
    metadata_editor.setup_ui(addnet_paste_params)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_edit
or.py", line 462, in setup_ui
    outputs=[addnet_paste_params[tabname][i]["module"], addnet_paste_params[tabname][i]["model"]],
IndexError: list index out of range
```

**Comment by 20171130** [comment]
I inspected modules.ui_components and did not find 'FormColumn'. Perhaps `git clone -b v2.0 https://github.com/camenduru/stable-diffusion-webui` is not as 'stable' as we may assume?

**Comment by camenduru** [comment]
thanks ❤
